name: Setup Rust Environment

inputs:
  key:
    description: Cache key
    required: true
  toolchain:
    description: Pass-through
    default: stable
    required: false
  components:
    description: Pass-through
    required: false
  target:
    description: Pass-through
    required: false

runs:
  using: composite
  steps:
    - name: Remove rustfmt
      run: rm -f ~/.cargo/bin/rustfmt ~/.cargo/bin/cargo-fmt
      shell: bash

    - name: Install Toolchain
      uses: dtolnay/rust-toolchain@v1
      id: toolchain-install
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        target: ${{ inputs.target }}

    - name: Set default toolchain
      run: rustup default ${{ inputs.toolchain }} || true
      shell: bash

    - name: Update self
      run: rustup self update || true
      shell: bash

    - name: Update
      run: rustup update || true
      shell: bash
