name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "58 7 * * 3"

jobs:
  lint-nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: rustfmt,rust-docs

      - run: cargo fmt --all -- --check
      - run: RUSTDOCFLAGS="-D warnings --cfg docsrs" cargo doc --package utcnow --all-features --no-deps

  lint-stable:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: clippy

      - run: cargo clippy --package utcnow --all-targets -- -D clippy::pedantic
      - run: cargo package --package utcnow

  check:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.48"
          - "1.56"
          - "1.58"
          - stable
          - nightly

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo check --package utcnow --all-targets
      - run: cargo clippy --package utcnow --all-targets -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.48"
          - "1.56"
          - "1.58"
          - stable
          - nightly
        platform:
          - ubuntu-20.04
          - windows-2022
          - macos-12

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo test --workspace -- --show-output
      - run: cargo test --workspace --no-default-features -- --show-output
      - run: cargo run --example minimal && date +%s.%9N
      - run: cargo run --example minimal --no-default-features && date +%s.%9N

  test-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: clippy

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: which wasm-pack || cargo install wasm-pack
      - run: wasm-pack test --node && date +%s.%9N
      - run: cargo clippy --target wasm32-unknown-unknown --package utcnow --all-targets -- -D warnings
      - run: cargo clippy --target wasm32-unknown-unknown --package utcnow --all-targets -- -D clippy::pedantic

  run-wasi:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: stable
          target: wasm32-wasi
          components: clippy

      - run: cargo clippy --target wasm32-wasi --package utcnow --all-targets -- -D warnings
      - run: cargo clippy --target wasm32-wasi --package utcnow --all-targets -- -D clippy::pedantic
      - run: curl https://wasmtime.dev/install.sh -sSf | bash
      - run: cargo build --target wasm32-wasi --example minimal
      - run: ~/.wasmtime/bin/wasmtime target/wasm32-wasi/debug/examples/minimal.wasm && date +%s.%9N

  cross-run-test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - wasm32-unknown-emscripten

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        id: actions-rs
        uses: ./.github/actions/setup-rust
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - run: cross rustc --target ${{ matrix.target }} -- --version || cargo +stable install cross --force
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D warnings
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D clippy::pedantic
      - run: cross test --target ${{ matrix.target }} --workspace -- --show-output
      - run: cross test --target ${{ matrix.target }} --workspace --no-default-features -- --show-output

  cross-execute:
    strategy:
      fail-fast: false
      matrix:
        target:
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-musl

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        id: actions-rs
        uses: ./.github/actions/setup-rust
        with:
          key: cross-run-test
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - run: cargo clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D warnings
      - run: cargo clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D clippy::pedantic
      - run: cargo test --target ${{ matrix.target }} --workspace -- --show-output
      - run: cargo test --target ${{ matrix.target }} --workspace --no-default-features -- --show-output
      - run: cargo run --example minimal && date +%s.%9N
      - run: cargo run --example minimal --no-default-features && date +%s.%9N

  cross-no-execute:
    strategy:
      fail-fast: false
      matrix:
        target:
          - thumbv7neon-linux-androideabi
          - x86_64-linux-android
          - x86_64-unknown-freebsd
          - x86_64-unknown-netbsd

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        id: actions-rs
        uses: ./.github/actions/setup-rust
        with:
          key: cross-no-execute
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - run: cross rustc --target ${{ matrix.target }} -- --version || cargo +stable install cross --force
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D warnings
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D clippy::pedantic
      - run: cross build --target ${{ matrix.target }} --examples
      - run: cross build --target ${{ matrix.target }} --examples --no-default-features

  cross-ios:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-ios
          - aarch64-apple-ios-sim
          - x86_64-apple-darwin
          - x86_64-apple-ios

    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        id: actions-rs
        uses: ./.github/actions/setup-rust
        with:
          key: cross-macos
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - run: cargo clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D warnings
      - run: cargo clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D clippy::pedantic
      - run: cargo build --target ${{ matrix.target }} --examples
      - run: cargo build --target ${{ matrix.target }} --examples --no-default-features

  cross-build-lib-only:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-fuchsia
          - x86_64-pc-solaris
          - x86_64-unknown-illumos
          - x86_64-unknown-redox

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        id: actions-rs
        uses: ./.github/actions/setup-rust
        with:
          key: cross-build-lib-only
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - run: cross rustc --target ${{ matrix.target }} -- --version || cargo +stable install cross --force
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D warnings
      - run: cross clippy --target ${{ matrix.target }} --package utcnow --all-targets -- -D clippy::pedantic
      - run: cross build --target ${{ matrix.target }} --workspace
      - run: cross build --target ${{ matrix.target }} --workspace --no-default-features

  minimal-versions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: minimal-versions

      - name: Update lockfile
        env:
          RUSTC_BOOTSTRAP: 1
        run: cargo generate-lockfile -Zminimal-versions

      - name: Test
        run: cargo test --all-targets -- --show-output

  audit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: audit

      - run: cargo update

      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  devskim:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif

  powerset:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - run: cargo hack --version || cargo install cargo-hack --force
      - run: cargo hack test --feature-powerset --include-features arbitrary,proptest,quickcheck,serde

  powerset-minimal-versions:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - run: cargo hack --version || cargo install cargo-hack --force

      - run: cargo generate-lockfile -Zminimal-versions
        env:
          RUSTC_BOOTSTRAP: 1

      - run: cargo hack test --feature-powerset --include-features arbitrary,proptest,quickcheck,serde
